version: '3.8'

services:
  postgres:
    image: postgres:15 # Use a specific PostgreSQL version
    container_name: comicmotion-postgres-dev
    environment:
      POSTGRES_USER: user # Replace with your desired user
      POSTGRES_PASSWORD: password # Replace with your desired password
      POSTGRES_DB: comicmotion_dev # Replace with your desired database name
    ports:
      - "5432:5432" # Map container port 5432 to host port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d comicmotion_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  temporal:
    image: temporalio/auto-setup:latest
    container_name: comicmotion-temporal-dev
    ports:
      - "7233:7233" # Default Temporal Frontend GRPC port
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PWD=password
      - POSTGRES_SEEDS=postgres
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local 