name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List all files after checkout
        run: ls -lR

      - name: Debug app lock file
        run: ls -l apps/comicmotion-app/package-lock.json

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
          cache-dependency-path: apps/comicmotion-app/package-lock.json

      # Cache Turborepo build cache for faster builds
      - name: Cache Turborepo
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install dependencies (with Turborepo support)
        run: npm install
        working-directory: .

      - name: Lint
        run: npm run lint
        working-directory: apps/comicmotion-app

      - name: Test
        run: npm run test
        working-directory: .

      - name: Debug Environment Variables Before Build
        env:
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
        run: |
          echo "Attempting to print relevant env vars:"
          echo "STRIPE_SECRET_KEY exists: $( [[ -z "${STRIPE_SECRET_KEY}" ]] && echo "No" || echo "Yes (masked)" )"
          echo "STRIPE_WEBHOOK_SECRET exists: $( [[ -z "${STRIPE_WEBHOOK_SECRET}" ]] && echo "No" || echo "Yes (masked)" )"
          echo "Listing all env vars containing STRIPE:"
          printenv | grep STRIPE || echo "No STRIPE vars found"
          echo "Listing all env vars containing NEXT:"
          printenv | grep NEXT || echo "No NEXT vars found"
        working-directory: . # Run this at the root where turbo runs

      - name: Build
        env:
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
          # You might need other env vars here depending on your app
          # For Clerk, if not using NEXT_PUBLIC_ prefix and needing them server-side during build:
          # CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
          # NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
          # NEXT_PUBLIC_CLERK_SIGN_IN_URL: /sign-in
          # NEXT_PUBLIC_CLERK_SIGN_UP_URL: /sign-up
          # NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL: /dashboard
          # NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL: /dashboard
        run: npm run build
        working-directory: .

      # Add deployment step here (e.g., Vercel, AWS, etc.)
      # - name: Deploy
      #   run: echo "Deploy step goes here"
      #   working-directory: .
